### PR TITLE
Windows 64: support for a testing setup

### PR DESCRIPTION
**Pull request by wint3ria**
# Description

**Update (27 Feb 2024)**

This PR is now ready for review. Windows can now be officially listed among our supported platforms, **with the experimental status**. Changes are as follows:

* Windows-specific environment setup and build facilities have been added. This includes lock files, cmd and powershell variants of the `setpath.sh` script, and GNU make target variants for kernel build.
* The entire test suite passes on Windows 11. This required fixing two bugs:
  * Incorrect path handling in data store component code. We now cast paths to their posix form before processing them.
  * Non-portable default integer type. Parts of our code was processing integer arrays and the insufficient precision on Windows (int32 vs int64 on Linux and macOS) would result in incorrect computation in specific circumstances. This is fixed for now, but I would expect similar issues in the future.

---

The current development architecture does not support win-64 platform. This is due to:
- The usage of non portable shell scripts
  - Makefile uses the "python3" binary that could be renamed python easily. I doubt it is necessary to be explicit on the fact we do not support python 2.
  - setpath.sh needs to be rewritten for powershell
- The lack of win-64 specific conda lock files (though pip locks can be used instead). This MR provides these lock files.
- The data store and its tests might need a bit of refactoring to fully support win-64.

## Testing Eradiate on Windows:

Please find attached the pytest output log. As one may notice, it mostly contains data file errors, due to the store implementation not being fully portable.
[log.txt](https://github.com/eradiate/eradiate/files/14222728/log.txt)

## Other issues:
- There seems to be a regression on the test `01_eradiate/02_system/test_irradiance_scaling.py::test_radiance_scaling` with the specific configurations:
  - `ckd_double-None-1.0-hdistant`
  - `ckd_double-None-1.0-mdistant`
  - `ckd_double-None-0.5-hdistant`
  - `ckd_double-None-0.5-mdistant`
- The CLI command `eradiate data fetch` often fails with network related issues. We could consider the implementation of a retry counter for each file.
- `make conda-init-tests` fails to produce an environment suitable for the pytest suite because it is missing seaborn.
- Conda lock files are only available for python 3.9, this should be fixed as part of our efforts in testing the solution.
- The current version of Eradiate can only be tested on Python 3.9, 3.10 or 3.11. Launching the pytest suite on python 3.12 would result in deps issues related to dateutils that has not been released yet:
```
(eradiate312) msp@175038c36576:~/git/eradiate$ pytest tests
ImportError while loading conftest '/home/msp/git/eradiate/tests/conftest.py'.
tests/conftest.py:5: in <module>
    import xarray as xr
../../.conda/envs/eradiate312/lib/python3.12/site-packages/xarray/__init__.py:3: in <module>
    from xarray import testing, tutorial
../../.conda/envs/eradiate312/lib/python3.12/site-packages/xarray/testing/__init__.py:1: in <module>
    from xarray.testing.assertions import (  # noqa: F401
../../.conda/envs/eradiate312/lib/python3.12/site-packages/xarray/testing/assertions.py:8: in <module>
    import pandas as pd
../../.conda/envs/eradiate312/lib/python3.12/site-packages/pandas/__init__.py:49: in <module>
    from pandas.core.api import (
../../.conda/envs/eradiate312/lib/python3.12/site-packages/pandas/core/api.py:1: in <module>
    from pandas._libs import (
../../.conda/envs/eradiate312/lib/python3.12/site-packages/pandas/_libs/__init__.py:18: in <module>
    from pandas._libs.interval import Interval
interval.pyx:1: in init pandas._libs.interval
    ???
hashtable.pyx:1: in init pandas._libs.hashtable
    ???
missing.pyx:1: in init pandas._libs.missing
    ???
../../.conda/envs/eradiate312/lib/python3.12/site-packages/pandas/_libs/tslibs/__init__.py:40: in <module>
    from pandas._libs.tslibs.conversion import localize_pydatetime
conversion.pyx:1: in init pandas._libs.tslibs.conversion
    ???
offsets.pyx:1: in init pandas._libs.tslibs.offsets
    ???
timestamps.pyx:1: in init pandas._libs.tslibs.timestamps
    ???
timedeltas.pyx:1: in init pandas._libs.tslibs.timedeltas
    ???
timezones.pyx:24: in init pandas._libs.tslibs.timezones
    ???
../../.conda/envs/eradiate312/lib/python3.12/site-packages/dateutil/tz/__init__.py:2: in <module>
    from .tz import *
../../.conda/envs/eradiate312/lib/python3.12/site-packages/dateutil/tz/tz.py:37: in <module>
    EPOCH = datetime.datetime.utcfromtimestamp(0)
E   DeprecationWarning: datetime.datetime.utcfromtimestamp() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.fromtimestamp(timestamp, datetime.UTC).
```

# Checklist

- [x] The code follows the relevant coding guidelines
- [x] The code generates no new warnings
- [x] The code is appropriately documented
- [x] The code is tested to prove its function
- [x] The feature branch is rebased on the current state of the `main` branch
- [x] I updated the change log if relevant
- [x] I give permission that the Eradiate project may redistribute my contributions under the terms of its license

### CODE REVIEW

**Comment by wint3ria** [comment]
Related to #373

**Comment by wint3ria** [comment]
@leroyvn I think there is enough matter to discuss. I will not be able to further work on this for the time being, but I think it is feasible to deliver the win-64 support for v0.26

**Comment by leroyvn** [comment]
Hi @wint3ria, thanks for this detailed report. Most of those issues are easy to fix. One point I'll comment on here (mostly for future reference): our "fail on warning" testing policy exists to detect warnings emitted by our own codebase—notably `DeprecationWarning`s. We don't want to fix third-party components, so until dateutils actually raises, we have no reason to take action and we can just ignore the warning using pytest config options.

**Comment by leroyvn** [comment]
Data store-related issues should be fixed now (I still have to commit to this branch but it's done).

**Comment by leroyvn** [comment]
I made progress on this by:

* isolating and fixing two platform-specific bugs;
* exploring how to get a fully functioning dev setup (including custom Mitsuba build);
* adding the basic components required to perform most dev tasks.

**Comment by leroyvn** [comment]
@wint3ria, this is ready for review. I'm realizing now that oddly, the environment variable setup part of the Conda env doesn't break anything although I didn't care to update it yet. I'll have a look at that as well.

**Comment by leroyvn** [comment]
I'll merge this now after a final check. I ended up implementing a different fix for the int overflow issue, I think it's a bit more robust.

**Pull request merged**
