### PR TITLE
Experiment

### PR DESCRIPTION
**Pull request by leroyvn**
# Description

This PR closes eradiate-issues#76. It deprecates the `SolverApp`/`Scene` abstractions in favour of a unified `Experiment` concept. Changes are as follows:

- Added a new `experiments` module
- Added new `Experiment` and `EarthObservationExperiment` interface classes
- Added new `OneDimExperiment` and `RamiExperiment` classes
- Added unit tests derived from the `SolverApp` line (with minor improvements)
- Updated API docs
- Deprecated `SolverApp` classes (to be removed later as part after integration in other products is done

# To do

- [x] Replace `SolverApp` instantiations with `Experiment` everywhere in the tests
- [ ] Replace `SolverApp` instantiations with `Experiment` everywhere in tutorials

# Checklist

- [x] The code follows the relevant coding guidelines
- [x] The code generates no new warnings
- [x] The code is appropriately documented
- [x] The code is tested to prove its function
- [x] The feature branch is rebased on the current state of the `main` branch
- [x] I give permission that the Eradiate project may redistribute my contributions under the terms of its license

### CODE REVIEW

**Comment by schunkes** [comment]
I took a look at the PR and checked out the branch. I think this approach feels much more intuitive than the split between Scene and SolverApp! :)

**Comment by leroyvn** [comment]
Basically finished, I won't patch tutorials now because we'll need to rewrite them for the next release anyway.

**Review by nollety — APPROVED** [review]
Unfortunately, I did not have the time to go through all the changes, but I love this concept of Experiment! It gives a nice scientific taste to our applications!

**Comment by leroyvn** [comment]
Let's merge this! Keep in mind, anyway, that the `SolverApp` classes are not going anywhere for now. I'll remove them when either tests will stop passing or when everyone on the team tells me that they are not required anymore.

**Pull request merged**
