### PR TITLE
Fix paths to CKD data sets in `downloads.yml`

### PR DESCRIPTION
**Pull request by nollety**
# Description

Fix the paths to the CKD data sets that are actually used by the `AFGL1986RadProfile` constructor. 

# Checklist

- [x] The code follows the relevant coding guidelines
- [x] The code generates no new warnings
- [x] The code is appropriately documented
- [x] The code is tested to prove its function
- [x] The feature branch is rebased on the current state of the `main` branch
- [x] I updated the change log if relevant
- [x] I give permission that the Eradiate project may redistribute my contributions under the terms of its license

### CODE REVIEW

**Comment by nollety** [comment]
All tests passed, but as far as I understand, this issue was not detected by failed tests?

**Comment by nollety** [comment]
Not sure if that deserves an entry in the changelog?

**Comment by leroyvn** [comment]
No, this is not a proper bug: in most cases, the missing file will be downloaded silently and things will go through without trouble. This is a problem only when you're getting ready for offline work: in that case, an outdated download list will result in critical files missing from the cache and offline work becomes impossible.

**Comment by leroyvn** [comment]
Thanks @nollety, this is merged.

**Pull request merged**
