### PR TITLE
Added thermoprops utilities for clouds

### PR DESCRIPTION
**Pull request by nollety**
# Description

I've added a function that computes the water vapor volume fraction at equilibrium, given pressure and temperature values. This function will be useful to adjust the gaseous atmospheric's thermophysical properties when clouds are added to the gaseous atmosphere.

⚠️ I've updated the dependencies to include `iapws`.

# Checklist

- [x] The code follows the relevant coding guidelines
- ~[ ]  The code generates no new warnings~
- [x] The code is appropriately documented
- [x] The code is tested to prove its function
- [x] The feature branch is rebased on the current state of the `main` branch
- [x] I give permission that the Eradiate project may redistribute my contributions under the terms of its license

### CODE REVIEW

**Comment by leroyvn** [comment]
Hi @nollety, the code seems alright to me. However, given how deep the changes due to the module reorganisation were, I'd appreciate if you could rebase onto `main` and make the required changes before I make a final thorough code review.

**Comment by nollety** [comment]
@leroyvn, it's rebased :)

**Review by leroyvn — APPROVED** [review]
Hi @nollety, seems fine to me. Please just squash and we'll merge this :)

**Comment by leroyvn** [comment]
Thanks, let's merge this!

**Pull request merged**
