### PR TITLE
4 variance based render tests

### PR DESCRIPTION
**Pull request by schunkes**
# Description

This PR introduces the first statistical render tests, similar to Mitsuba. The first available test runs the HET04 or "real zoom in" canopy scene.

Closes [4](https://github.com/eradiate/eradiate-issues/issues/4)

# Checklist

- [ ] The code follows the relevant coding guidelines
- [x] The code generates no new warnings
- [x] The code is appropriately documented
- [x] The code is tested to prove its function
- [ ] The feature branch is rebased on the current state of the `main` branch
- [ ] I give permission that the Eradiate project may redistribute my contributions under the terms of its license

### CODE REVIEW

**Comment by schunkes** [comment]
About @leroyvn's comment in the issue: I am not sure I can import the utility functions from Mitsuba, because they are defined in `src/librender/tests` and I can't easily import from that.

**Comment by leroyvn** [comment]
HI @schunkes, thanks for the PR, very happy to have this kind of tests in our suite :) I see that the PR is marked as draft, do you want me to review it extensively or are you expecting a quick scan for coarse-grained comments?

**Comment by schunkes** [comment]
I am already making additional changes, so for the moment you can take a short look but don't spend much time on it. Also: Do you have an idea for importing the utility functions from mitsuba? Otherwise I'll just leave my copies in my code.

**Comment by leroyvn** [comment]
> you can take a short look but don't spend much time on it

Ok, I'll wait until you tell me it's ready for review then 👌 

> Do you have an idea for importing the utility functions from mitsuba?

No, and I don't think there is an elegant way to do so. You can just copy the code: if making this a lib component ever becomes relevant, we'll see what to do.

**Comment by leroyvn** [comment]
I think given the progress on #171, we should close this. @schunkes?

**Pull request closed without merging**
