### PR TITLE
Solar irradiance spectrum datasets

### PR DESCRIPTION
**Pull request by nollety**
# Description

This pull request closes eradiate/eradiate-issues#29 and #2. Partially addresses eradiate/eradiate-issues#23.

Changes are:
- data submodule update (solar irradiance spectrum datasets were updated and the `solid_2017_mean` dataset was added)
- documented the (new) format of the solar irradiance spectrum datasets in  `data/solar_irradiance_spectra` (is that the right place?)
- updated data tests
- updated `scenes.spectra` with respect to the new format for solar irradiance spectrum
- the metadata specifications for solar irradiance spectrum datasets are defined in `util.xarray` (is that the right place?)
- changed the alias `whi_2008 -> whi_2008_time_period_1` to `whi_2008 -> whi_2008_time_period_3`. After reading the article describing the `whi_2008_*` datasets, it seems to me as this was the most appropriate choice.
- updated the table that lists the available solar irradiance spectrum datasets. That table now also provides the datasets spectral resolutions and indicates if the dataset has a non-empty time coordinate.
- added a page in the user guide about solar irradiance spectra. It provides a quick description of the available datasets -- this should help the user in making a choice of the dataset to use -- and explains how to list the available datasets and visualise the solar irradiance spectrum corresponding to one dataset. Since this is my first contribution to the user guide, feedback is welcome!
- added a tutorial notebook about how to add your own solar irradiance spectrum dataset. This was a good exercise for me, but I'm wondering about how useful this is. Let me know^^

# Checklist

- [x] The code follows the relevant coding guidelines
- [x] The code generates no new warnings
- [x] The code is apropriately documented.
- [x] The code is tested to prove its function
- [x] The feature branch is rebased on the current state of the `main` branch
- [x] I give permission that the Eradiate project may redistribute my contributions under the terms of its license

### CODE REVIEW

**Comment by nollety** [comment]
@leroyvn I just pushed another 2 commits because I realised that `SolarIrradianceSpectrum` would have to be modified to support solar irradiance spectrum datasets with a time coordinate (the only case is the `solid_2017` dataset). I made the `SolarIrradianceSpectrum.kernel_dict()` method to raise NotImplementedError when the class is built with the `solid_2017` dataset.

**Review by leroyvn — COMMENTED** [review]
Hi @nollety, this is a nice PR. I have only one comment regarding the logical structure you used to include your tutorial, it's easy to address (either now or later, it's not critical). If you could just squash those commits, then we can process and merge :)

**Comment by nollety** [comment]
@leroyvn I'm glad that you liked this PR. I moved the tutorial notebook as a subsection of the user guide section on solar irradiance spectra as you suggested, thanks for that tip! I squashed the commits, this is ready to be merged :)

**Comment by leroyvn** [comment]
Hi @nollety, is this PR now ready for merge?

**Comment by nollety** [comment]
Yes, it's ready!

**Comment by nollety** [comment]
@leroyv I'm hesitant to push the rebased branch now because `tests/system/test_sanity` fails since the rebase.

**Comment by nollety** [comment]
@leroyvn following our discussion of yesterday, I ignored the failing test `test_sanity.py` since it fails only on my machine and fails not only on this branch but also fails on the latest `main` (on my machine), and would probably be fixed after I recompile the kernel.

This PR is ready again for merge.

**Comment by leroyvn** [comment]
Let's go: I'll merge this now!

**Pull request merged**
